include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat missing required params as errors (not warnings)
    missing_required_param: error
    missing_return: error
  exclude:
    # Exclude generated files from analysis
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Style
    - always_declare_return_types
    - annotate_overrides
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_unnecessary_containers
    - avoid_void_async
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - constant_identifier_names
    - directives_ordering
    - empty_catches
    - file_names
    - flutter_style_todos
    - hash_and_equals
    - library_names
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - non_constant_identifier_names
    - overridden_fields
    - package_names
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_is_not_empty
    - prefer_single_quotes
    - require_trailing_commas
    - sort_child_properties_last
    - unnecessary_breaks
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_checks
    - unnecessary_statements
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
    - valid_regexps
